animations {
    enabled = yes

    bezier = vantaSnap, 0.1, 1, 0.1, 1
    bezier = vantaLinear, 0, 0, 1, 1
    bezier = quick, 0.15, 0, 0.1, 1

    animation = windows,        1, 3.0,  vantaSnap, popin 70%
    animation = windowsIn,      1, 3.0,  vantaSnap, popin 70%
    animation = windowsOut,     1, 2.0,  vantaSnap, popin 70%
    
    animation = workspaces,     1, 4.0,  vantaSnap, slide
    animation = workspacesIn,   1, 4.0,  vantaSnap, slide
    animation = workspacesOut,  1, 4.0,  vantaSnap, slide
    
    animation = border,         1, 1.0,  quick
    animation = fade,           1, 2.0,  vantaLinear
    animation = layers,         1, 3.0,  vantaSnap, fade
}
