$color0  = rgba(000000ff)   # Absolute Black
$color1  = rgba(D32F2Fff)   # MAGI Red (Active/Primary)
$color2  = rgba(388E3Cff)   # Tactical Green
$color3  = rgba(FFB300ff)   # Warning Amber
$color4  = rgba(B71C1Cff)   # Dark Blood Red
$color5  = rgba(F57C00ff)   # Industrial Orange
$color6  = rgba(455A64ff)   # Steel Grey
$color7  = rgba(E0E0E0ff)   # Light Grey
$color8  = rgba(1A0808ff)   # Dim Dark Red (Inactive)
$color9  = rgba(D32F2Fff)   # MAGI Red
$color10 = rgba(388E3Cff)   # Tactical Green
$color11 = rgba(FFB300ff)   # Warning Amber
$color12 = rgba(B71C1Cff)   # Dark Blood Red
$color13 = rgba(F57C00ff)   # Industrial Orange
$color14 = rgba(455A64ff)   # Steel Grey
$color15 = rgba(FFFFFFFF)   # Pure White
$font    = "JetBrains Mono Nerd Font"
$rounding = 0
$wallpaper = ~/.config/hypr/themes/current/wallpapers/main.png
