#!/bin/bash
# ============================================================
# Chameleon Theme — GTK Settings
# Applies a neutral dark GTK base; pywal handles accent colors
# via gtk4.css generated by chameleon-chwall.sh.
# ============================================================

# GTK base theme (dark neutral — pywal adds accent overrides)
gsettings set org.gnome.desktop.interface gtk-theme "Adwaita-dark"
gsettings set org.gnome.desktop.wm.preferences theme "Adwaita-dark"

# Icons, cursor, font
if command -v gsettings > /dev/null 2>&1; then
    gsettings set org.gnome.desktop.interface icon-theme "Papirus-Dark"
    gsettings set org.gnome.desktop.interface cursor-theme "Bibata-Modern-Classic"
    gsettings set org.gnome.desktop.interface cursor-size 24
    gsettings set org.gnome.desktop.interface font-name "Inter 11"
    gsettings set org.gnome.desktop.interface color-scheme "prefer-dark"
fi

# GTK4 accent colors are written by chameleon-chwall.sh from pywal
# into ~/.config/gtk-4.0/gtk.css directly — no copy needed here.

# Force file manager restart to pick up new CSS
pkill nautilus 2>/dev/null || true
pkill thunar 2>/dev/null || true
