# Alpine Linux overrides
NetworkManager=networkmanager
font-jetbrains-mono-nerd=font-jetbrains-mono-nerd
nerd-fonts=font-nerd-fonts-symbols
pywal=
python3=python3
bat=bat
kvantum=
qt5ct=
qt6ct=
nwg-look=
swww=
wlogout=
cliphist=
papirus-icon-theme=papirus-icon-theme
