# Arch Linux family overrides
NetworkManager=networkmanager
font-jetbrains-mono-nerd=ttf-jetbrains-mono-nerd
nerd-fonts=ttf-nerd-fonts-symbols
pywal=python-pywal
python3=python
wl-clipboard=wl-clipboard
papirus-icon-theme=papirus-icon-theme
