# Debian/Ubuntu family overrides
NetworkManager=network-manager
font-jetbrains-mono-nerd=fonts-jetbrains-mono
nerd-fonts=
pywal=
bat=bat
kvantum=qt5-style-kvantum
rofi-wayland=rofi
papirus-icon-theme=papirus-icon-theme
swww=
wlogout=
nwg-look=
cliphist=
swayidle=swayidle
fastfetch=
eza=
python3=python3
qt6ct=
