# Fedora/RPM family overrides
font-jetbrains-mono-nerd=jetbrains-mono-fonts-all
nerd-fonts=
pywal=
kvantum=kvantum
python3=python3
papirus-icon-theme=papirus-icon-theme
swww=
wlogout=
cliphist=
nwg-look=
