# Gentoo overrides (category/package format)
NetworkManager=net-misc/networkmanager
waybar=gui-apps/waybar
kitty=x11-terms/kitty
thunar=xfce-base/thunar
dunst=x11-misc/dunst
rofi-wayland=x11-misc/rofi
font-jetbrains-mono-nerd=media-fonts/nerd-fonts
nerd-fonts=media-fonts/nerd-fonts
pywal=
bat=sys-apps/bat
python3=dev-lang/python
grim=gui-apps/grim
slurp=gui-apps/slurp
wl-clipboard=gui-apps/wl-clipboard
brightnessctl=sys-power/brightnessctl
blueman=net-wireless/blueman
pavucontrol=media-sound/pavucontrol
zsh=app-shells/zsh
kvantum=x11-themes/kvantum
papirus-icon-theme=x11-themes/papirus-icon-theme
swww=
wlogout=
cliphist=
nwg-look=
fastfetch=
eza=
swayidle=gui-apps/swayidle
qt5ct=x11-misc/qt5ct
qt6ct=x11-misc/qt6ct
