# openSUSE family overrides
font-jetbrains-mono-nerd=jetbrains-mono-fonts
nerd-fonts=
pywal=
kvantum=kvantum-manager
python3=python3
papirus-icon-theme=papirus-icon-theme
swww=
wlogout=
cliphist=
nwg-look=
