# Void Linux overrides (reference distro)
# Void uses capitalized package names in some cases
NetworkManager=NetworkManager
font-jetbrains-mono-nerd=nerd-fonts-ttf
nerd-fonts=nerd-fonts-symbols-ttf
pywal=pywal
bat=bat
kvantum=kvantum
rofi-wayland=rofi-wayland
swww=swww
python3=python3
waybar=Waybar
nwg-look=nwg-look
wl-clipboard=wl-clipboard
papirus-icon-theme=papirus-icon-theme
