#!/usr/bin/env python3
# generate-eww-theme.py
# Reads the active theme's colors.conf and generates ~/.config/eww/theme-vars.scss
# Called by switch-theme.sh after every theme change.

import re, os

COLORS_CONF = os.path.expanduser("~/.config/hypr/themes/current/colors.conf")
OUTPUT      = os.path.expanduser("~/.config/eww/theme-vars.scss")

def parse_hex(line):
    m = re.search(r'(?:rgb\(|rgba\(|#)([0-9a-fA-F]{6})', line)
    return m.group(1) if m else None

# Sensible defaults (catppuccin mocha)
colors = {
    "accent":    "cba6f7",
    "accent_bg": "313244",
    "text":      "cdd6f4",
    "subtext":   "a6adc8",
    "bg":        "1e1e2e",
}

try:
    with open(COLORS_CONF) as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith("#"):
                continue
            h = parse_hex(line)
            if not h:
                continue
            if "active_border" in line and "inactive" not in line:
                colors["accent"] = h
            elif "inactive_border" in line:
                colors["accent_bg"] = h
            elif "color7" in line:
                colors["text"] = h
            elif "color6" in line:
                colors["subtext"] = h
            elif "color0" in line:
                colors["bg"] = h
                colors["accent_bg"] = h
except FileNotFoundError:
    pass

def hex_to_scss(h):
    r, g, b = int(h[0:2],16), int(h[2:4],16), int(h[4:6],16)
    return f"rgba({r},{g},{b},1)"

scss = "// Auto-generated by generate-eww-theme.py — DO NOT EDIT\n\n"
for name, hex_val in colors.items():
    scss += f"${name}: {hex_to_scss(hex_val)};\n"

with open(OUTPUT, "w") as f:
    f.write(scss)

print(f"Eww theme-vars written → accent #{colors['accent']}")
