#!/usr/bin/env python3
# generate-swayosd-style.py
# Reads the active theme's colors.conf and generates ~/.config/swayosd/style.css
# Called by switch-theme.sh after every theme change.

import re
import os
import shutil

COLORS_CONF = os.path.expanduser("~/.config/hypr/themes/current/colors.conf")
TEMPLATE    = os.path.expanduser("~/.config/swayosd/style.css.template")
OUTPUT      = os.path.expanduser("~/.config/swayosd/style.css")

def parse_hex(line):
    """Extract a hex color (6 chars) from a line like '$active_border = rgb(cba6f7)'"""
    m = re.search(r'(?:rgb\(|rgba\(|#)([0-9a-fA-F]{6})', line)
    return m.group(1) if m else None

# Read colors.conf
accent_hex   = "cba6f7"   # sensible default (catppuccin mauve)
bg_hex       = "1e1e2e"

try:
    with open(COLORS_CONF) as f:
        for line in f:
            if "active_border" in line and "inactive" not in line:
                h = parse_hex(line)
                if h:
                    accent_hex = h
            if any(k in line for k in ("color0", "$base", "$background")):
                h = parse_hex(line)
                if h:
                    bg_hex = h
except FileNotFoundError:
    pass

# Convert hex to rgb tuples for GTK-style @define-color
def hex_to_rgb(h):
    r, g, b = int(h[0:2],16), int(h[2:4],16), int(h[4:6],16)
    return r, g, b

ar, ag, ab = hex_to_rgb(accent_hex)
br, bg_b, bb = hex_to_rgb(bg_hex)

css_header = f"""/* Auto-generated by generate-swayosd-style.py — DO NOT EDIT */
@define-color accent     rgb({ar},{ag},{ab});
@define-color accent_bg  rgb({br},{bg_b},{bb});

"""

with open(TEMPLATE) as f:
    template = f.read()

output = css_header + template.replace("@accent_bg", "@accent_bg").replace("@accent", "@accent")

with open(OUTPUT, "w") as f:
    f.write(output)

print(f"SwayOSD style written → accent #{accent_hex}")
