general {
    no_fade_in = false
    grace = 0
    ignore_empty = false
}

background {
    monitor =
    path = ~/.config/hypr/themes/Vanta-Black/wallpapers/makima_is_listening.jpg
    blur_passes = 2
    blur_size = 5
    color = rgba(0, 0, 0, 1.0)
}

input-field {
    monitor =
    size = 400, 60
    outline_thickness = 3
    dots_size = 0.2
    dots_spacing = 0.5
    dots_center = true
    outer_color = rgb(224, 224, 224)
    inner_color = rgba(0, 0, 0, 0.9)
    font_color = rgb(255, 255, 255)
    font_family = JetBrains Mono Nerd Font
    fade_on_empty = false
    placeholder_text = "Unlock Vanta-Black"
    hide_input = false
    check_color = rgb(200, 200, 200)
    fail_color = rgb(255, 255, 255)
    fail_text = "Access Denied"
}
