# One Dark — Hyprlock Config

background {
    path = ~/.config/hypr/themes/current/wallpapers/main.png
    blur_passes = 3
    blur_size = 6
    brightness = 0.6
}

input-field {
    size = 250, 50
    outline_thickness = 2
    dots_size = 0.25
    dots_spacing = 0.2
    dots_center = true
    outer_color = rgb(c678dd)
    inner_color = rgb(282c34)
    font_color = rgb(abb2bf)
    fade_on_empty = true
    placeholder_text = <i>Password...</i>
    hide_input = false
    position = 0, -120
    halign = center
    valign = center
    rounding = 14
}

label {
    text = $TIME
    color = rgb(abb2bf)
    font_size = 64
    font_family = JetBrains Mono Nerd Font
    position = 0, 80
    halign = center
    valign = center
}
