# Vanta Black Kitty Theme

foreground              #FFFFFF
background              #000000
selection_foreground    #000000
selection_background    #FFFFFF

cursor                  #FFFFFF
cursor_text_color       #000000

url_color               #FFFFFF

active_border_color     #FFFFFF
inactive_border_color   #333333
bell_border_color       #FFFFFF

wayland_titlebar_color  system
macos_titlebar_color    system

active_tab_foreground   #FFFFFF
active_tab_background   #000000
inactive_tab_foreground #FFFFFF
inactive_tab_background #000000
tab_bar_background      #FFFFFF

mark1_foreground        #000000
mark1_background        #FFFFFF
mark2_foreground        #000000
mark2_background        #FFFFFF
mark3_foreground        #000000
mark3_background        #FFFFFF

# Normal colors
color0  #090f15
color8  #262e36

color1  #6c6d74
color9  #6c6d74

color2  #b3b7ba
color10 #b3b7ba

color3  #d3d1ce
color11 #d3d1ce

color4  #6c6d74
color12 #6c6d74

color5  #b3b7ba
color13 #b3b7ba

color6  #d3d1ce
color14 #d3d1ce

color7  #d3d1ce
color15 #d3d1ce
