general {
    no_fade_in = false
    grace = 0
    ignore_empty = false
}

background {
    monitor =
    path = ~/.config/hypr/themes/current/wallpapers/main.png
    blur_passes = 2
    blur_size = 5
}

input-field {
    monitor =
    size = 400, 60
    outline_thickness = 4
    dots_size = 0.2
    dots_spacing = 0.5
    dots_center = true
    outer_color = rgb(255, 179, 0)
    inner_color = rgba(0, 0, 0, 0.9)
    font_color = rgb(255, 255, 255)
    fade_on_empty = false
    placeholder_text = "[ ENTER AUTHORIZATION CODE ]"
    hide_input = false
    check_color = rgb(56, 142, 60)
    fail_color = rgb(211, 47, 47)
    fail_text = "EMERGENCY // LOCKDOWN"
}
