general {
    no_fade_in = false
    grace = 0
    ignore_empty = false
}

background {
    monitor =
    path = ~/.config/hypr/themes/Midnight-Slate/wallpapers/makima_is_listening.jpg
    blur_passes = 2
    blur_size = 5
    color = rgb(9, 15, 21) # Midnight
}

input-field {
    monitor =
    size = 400, 60
    outline_thickness = 3
    dots_size = 0.2
    dots_spacing = 0.5
    dots_center = true
    outer_color = rgb(108, 109, 116) # Apres Ski
    inner_color = rgb(9, 15, 21) # Midnight
    font_color = rgb(211, 209, 206) # Arctic
    font_family = JetBrains Mono Nerd Font
    fade_on_empty = false
    placeholder_text = "Unlock Midnight-Slate"
    hide_input = false
    check_color = rgb(179, 183, 186) # Slopes
    fail_color = rgb(211, 209, 206) # Arctic
    fail_text = "Access Denied"
}
